apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acom-offer-desk-pilot
resources:
  - resources/workloads/backend.yaml
  - resources/workloads/web.yaml
  - resources/workloads/notifications-worker.yaml
  - resources/networking/ingress.yaml
  - resources/networking/networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: acom-offer-desk
      acom.deploy/environment: pilot
commonAnnotations:
  acom.deploy/sha: "7aba20a5a9fda02112952dfac841c168d1298178"
