services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: ["start", "--config", "/etc/ngrok.yml", "public"]
    env_file:
      - .env
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - "4040:4040"
    networks:
      - project_net

networks:
  project_net:
    name: project_net
