apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acom-offer-desk-pilot
configMapGenerator:
  - name: pilot-job-scripts
    files:
      - ../../scripts/write-pilot-env.py
      - ../../scripts/keycloak-init-deploy-k8s.sh
      - ../../scripts/post-deploy-verify-k8s.sh
    options:
      disableNameSuffixHash: true
resources:
  - resources/namespace.yaml
  - resources/rbac/secrets-rbac.yaml
  - resources/config/rabbitmq-configmap.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: acom-offer-desk
      acom.deploy/environment: pilot
