export const ROLE = {
  SUPERADMIN: 1,
  ADMIN: 2,
  CONTRACTOR: 3,
  PROJECT_MANAGER: 4,
  LEAD_ECONOMIST: 5,
  ECONOMIST: 6,
  OPERATOR: 7
} as const;

export const ECONOMIST_MANAGEMENT_ROLES = [ROLE.SUPERADMIN, ROLE.ADMIN, ROLE.LEAD_ECONOMIST] as const;