apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pilot-jobs-migrate
  namespace: flux-system
spec:
  dependsOn:
    - name: pilot-infra
  interval: 10m
  timeout: 15m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: acomofferdesk
  path: ./deploy/k8s/pilot/flux-phases/jobs-migrate
