apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: acom-offer-desk-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        acom.security/tier: app
    spec:
      serviceAccountName: acom-pilot-runtime
      containers:
        - name: web
          image: acom-web:8ea43577e06e
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: acom-offer-desk-pilot
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
