parent=keycloak.v2
import=common/keycloak
locales=ru,en
darkMode=false
scripts=js/submit-state.js?v=__AOD_ASSET_VERSION__
aodAssetVersion=__AOD_ASSET_VERSION__
aodSupportUrl=https://max.ru/u/f9LHodD0cOIA4s2RhH3dW5NoCLRn88NF67UYfQe_rOnnM6Y1a7VW_vOUt5I
aodBitrixUrl=https://team.alabuga.ru/company/structure.php?set_filter_structure=Y&structure_UF_DEPARTMENT=8304&filter=Y&set_filter=Y
